### ISSUE TITLE
lgZoom Plugin improvement: no more blurry images

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1055]
Currently the zoom plugin works simply with a css transform-scale.

This of course enlarges the image, but also makes it very blurry. Especially on cell phones it is a disaster.

The zoom functionality should zoom to the real / a higher pixel height and width / the image should not be css scaled in the zoomed view.

BTW: That’s the way it works in fancybox - fancybox uses css scale only for the zoom effect. after the effect ends it resets the css scale and sets new height and width for the (now oversized) image frame.

**Comment by sachinchoolur** [comment]
Hey @amkdev,

Thank you for the feedback. lightGallery does not scale images beyond their actual size. So it is basically the same as using width and height. I think both approaches have their own pros and cons. Using transform doesn't cause content reflow and repaint and also reduces unwanted computations. 

But, for sure I'll evaluate the solution you suggested. removing the scale property once the image is zoomed to 100% is not hard to implement. I'll try to implement this if it has any advantages

**Comment by amkdev** [comment]
I was probably a bit wrong ... I checked the behaviour again.

I looks like, that only the mobile browser working different to the desktops. See this screenshot:

reft is the FF desktop mobile preview, right is iOS:
![screenshot](https://filedn.eu/lvNJb3evvCaJllikakOypfS/screenshot.png)

I am sure if you do without css-transform you would also tell a better result on the safari. But probably there is another tweak to change this too ... I will also do some more research.

**Comment by sachinchoolur** [comment]
Thanks for the screenshots. Are you using responsive images?

**Comment by amkdev** [comment]
Size in Pixel is 1520 x 1017 ... my thought was it's maybe to much so iOS-Safari downscales too much and so looses details. I'm at a bit of a loss. I have also researched a lot and found nothing really constructive.

**Comment by amkdev** [comment]
Maybe you use an iPhone... try it out when you have time.

https://photos.alexander-korn.de/en/__home__/india-2014/agra

**Comment by sachinchoolur** [comment]
I've tested it on my iPhone. But could not find any issues. I'll evaluate the approach you suggested and try to implement if makes any difference

**Comment by amkdev** [comment]
Some more Screenshots - and it's not only on my side with my pictures or on mobile only. Also with you demos but almost all you demo images are dark and detailless - but check the mushroom. ;)  

There must be a reason why other galleries do zooming in another way ;) - GLightbox is also a good example (but lags on other features)

You should reopen this issue ... lightGallery is strong in a lot of features but on zoom quality it simply fails. sorry. ;) 

BTW: the scale setting doesnt take any effect on my side. I can define 1 or 2 or 5 … makes no difference at all.

![screenshot](https://filedn.eu/lvNJb3evvCaJllikakOypfS/lG-zoom1.jpg)

![screenshot](https://filedn.eu/lvNJb3evvCaJllikakOypfS/lG-zoom2.jpg)

**Comment by joshuaiz** [comment]
Same issue for me. The images on mobile are noticably and demonstrably more blurry when zoomed than on desktop.

**Comment by sachinchoolur** [comment]
The issue has been fixed locally along with many other improvements. 
I'm working on improving the video module currently.  Once that is done, I'll publish the zoom changes.

**Comment by arrstemmler** [comment]
Hey @sachinchoolur,
In Version 2.3.0 the bug still exists. Are you working on a fix? Maybe its better to reopen this issue for better transparency?
Thanks in advance
