### ISSUE TITLE
zoom plugin laggy in firefox.

### ISSUE THREAD

**Issue by wwwonka** [sachinchoolur/lightGallery#1080]
In Firefox 89.0.2 on macOS Mojave 10.14.6,  I've been noticing some heavy frame dropping during the zoom transition from the gallery to the lightview. Weird behaviour since everything runs buttery smooth in Safari and quite good in Chrome as well.

I could copy-paste my code but simpler is to go on the library official website where the exact same behaviour manifests as well.

Is this expected and is there something to be done about it? Perhaps adding some missing vendor-prefixes somewhere?

**Comment by sachinchoolur** [comment]
Hey @wwwonka,

Thank you for reporting this. I'll look into this and get back to you.

**Comment by sachinchoolur** [comment]
The transition was working smoothly for me on firefox. However, it was throwing a warning about "will-change" memory conception. This has been fixed in version [2.1.8](https://github.com/sachinchoolur/lightGallery/commit/090965acf74f96e15fcea2546b85ecb5c9ac5293). Please check and let me know if the issue persists

**Comment by wwwonka** [comment]
It seems a little bit better but it's still the least smoot of all the browsers.

I've noticed the warning still shows in the console when the browser is using the whole screen but not when it's resized to a smaller size. My high resolution image is 1500x1500 and just for reference here is a screenshot of the warning:

<img width="1192" alt="firefox_devtools_will change" src="https://user-images.githubusercontent.com/16738328/124978452-cc2ba900-dfff-11eb-8919-2ae52acf6b27.png">

**Comment by wwwonka** [comment]
Ok nevermind I had a fancy blur filter animating behind the gallery set to will-change in one of my CSS files. Once removed, the warning disappears and the transition is smooth.

**Comment by sachinchoolur** [comment]
Thanks for the update.  Closing the issue as it is resolved. 
I'll look spend some more time on the animation performance and try to improve it if possible

**Comment by wwwonka** [comment]
Speaking on top of my head but maybe using `requestAnimationFrame()` could be an option?
