### ISSUE TITLE
Blurry images when zooming on iOS devices

### ISSUE THREAD

**Issue by arrschmitt** [sachinchoolur/lightGallery#1260]
## Description

The feature requested in https://github.com/sachinchoolur/lightGallery/issues/1055 seems not to work on iOS Devices (e.g. iPhone X). We've tested with the latest lightgallery version 2.4.0.

See these screenshots:

Firefox desktop mobile preview with simulated iPhone SE:

![firefox_simluation](https://user-images.githubusercontent.com/22952558/155526933-31d0aa66-911c-42ca-b554-6f9ff001bbaf.png)

Real iPhoneX Screenshot:

![iPhoneX](https://user-images.githubusercontent.com/22952558/155526943-ac23a165-f695-4c24-9393-38c123e62c0d.png)

### Environment

-   Browser and version - Safari 13.1
-   OS - iOS Catalina
-   lightGallery version - 2.4.0

### Additional context

We will purchase the team license, but only if this feature also works on iOS.

**Comment by sachinchoolur** [comment]
Hey @arrschmitt,

The fix is not included in version 2.4.0. I'm currently working on the zoom module and hope It will be ready by this week

**Comment by JVital2013** [comment]
I just tested the new commit on the lg-zoom branch. It looks like it fixes the issue for me on iOS devices!

I look forward to the final release, but thanks for your hard work!

**Comment by sachinchoolur** [comment]
Sure, I'm re-writing the zoom module completely. I'll try to complete it ASAP

**Comment by smerriman** [comment]
@JVital2013 Where is the commit that was working for you? Have tried several different versions, including the latest betas, but all are still giving blurry iOS images. Even if not released yet, would be good to have some version that's working since zoom is important for my site.

**Comment by sachinchoolur** [comment]
Hey @smerriman ,
It is in https://github.com/sachinchoolur/lightGallery/tree/lg-zoom branch. Due to a product release, I couldn't work on this feature in the last few days. But, I hope it will be completely ready in a few days

**Comment by smerriman** [comment]
@sachinchoolur Unfortunately, that branch isn't helping at all - here's a barebones example:

https://www.cre8d-design.com/lgtest/test.html

Despite being a high-res image, zooming on iOS shows the image in very low quality, while other devices / computers work fine.

**Comment by smerriman** [comment]
OK, I think I see - there's a modified version in the src folder, but it hasn't been built in a way that's usable on a website currently (I was using the dist folder in that branch).

**Comment by JVital2013** [comment]
You need to build it yourself right now; clone the branch and run `npm run-script build`. For me that was easier said than done, but I've attached my build in case you run into issues

[lightgallery-96d8c17.zip](https://github.com/sachinchoolur/lightGallery/files/8600101/lightgallery-96d8c17.zip)
.

**Comment by smerriman** [comment]
Thanks! Unfortunately, even that version isn't working on iOS for me - but hopefully a working version will end up in the beta release soon.

**Comment by smerriman** [comment]
@sachinchoolur I really don't want to be pushy as I'm sure you have other priorities, but we have a site launching soon where a zoom feature is vital (it's being used for floor plans).

Given you mentioned "a few days" I've been deferring the client saying it will be fixed in time for launch - but that was a couple of weeks ago (and you also said "ASAP" two months ago).

Totally understand these things can be hard to estimate etc, but if there's a chance it's not going to be resolved soon, I'd rather simply know so that I can start looking for an alternative solution.

PS - I see that in the package JVital2013 uploaded, it works if you enable the zoom-to-full-size option - but it doesn't work if clicking the icons to zoom in/out partially, or pinch-zooming. I'm guessing your plan is to set the width/height on every zoom level, rather than only when it reaches max-size.

**Comment by smerriman** [comment]
Actually, I've just been doing more research on this and it seems like a lot of other libraries have the same issue; the cause is that when hardware acceleration is enabled via CSS on the image, it doesn't re-render the image when zooming in.

So it may not even be "solvable" - other libraries have said it's a problem with mobile Safari that would need to be fixed on their end.

I've found a very quick workaround - in setZoomStyles, changing the translate3d and scale3d CSS to their 2d forms to prevent hardware acceleration. This is of course 'slower', and other libraries have decided against doing this - but for my use case it at least works, so is probably what I'll go with.

**Comment by sachinchoolur** [comment]
Hey @smerriman,

Really sorry for the delay. Yes, got busy with some other task. 
But, this is my highest priority task now. 

When are you releasing your product? I'll try to complete before that

**Comment by arrstemmler** [comment]
Hi @sachinchoolur ,
do you have any news about the issue?
Its a must have for our customer.
Otherwise we have to switch to another plugin.

**Comment by sachinchoolur** [comment]
Yes, it is completed. doing final testing..

**Comment by davlasq** [comment]
@sachinchoolur when can we expect update? It's very important feature for my project

**Comment by sachinchoolur** [comment]
Releasing a new version with the fix today or tomorrow

**Comment by sachinchoolur** [comment]
The issue has been fixed in version [2.6.0-beta.1](https://github.com/sachinchoolur/lightGallery/releases/tag/2.6.0-beta.1)

I'm really sorry for the delay and thank you for your patience!

**Comment by fw42** [comment]
I'm still seeing the same (or a very similar?) problem on 2.7.1-beta.0. What I'm seeing is that the zoom is sharp when I double tap the screen to get to the max zoom, but when I pinch zoom into a state that is zoomed in but not all the way, then it's still blurry.

**Comment by vitoriowingert** [comment]
Hi guys!
Anyone found a good fix to this problem mentioned by @fw42 ?
I'm having the same problem here, if I pinch zoom the imagem still blurry, but when get 100% of zoom the blur is not there more 😵‍💫
