### ISSUE TITLE
Jumping of max zoomed in images

### ISSUE THREAD

**Issue by mo-we** [sachinchoolur/lightGallery#1423]
## Description

When i max zoom in an image until the actual size, the auto width and height are changed to the actual size width and height, also the transform gets overwritten with `!important` with the `reset-transition` -rule: https://github.com/sachinchoolur/lightGallery/commit/d90e2e84e0d99f2d0674d74d07bd27fb45e2da04#r88744543

I also attached a short screencast about the Issue

### Steps to reproduce

- include a big enough picture (bigger than the browser window/container)
- use the zoom-plugin
- zoom in until the actual size of the picture.

### JS code that you use to initialize lightGallery.

```js

    galleryWrap.forEach((gallery) => {
      lightGallery(gallery, {
        download: false,
        counter: false,
        actualSize:false,
        showZoomInOutIcons: true,
        mobileSettings: {
          controls: false,
          showCloseIcon: true,
          download: false,
        },
        licenseKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      })
    })
```

### Environment

-   Browser and version - All
-   OS - Ubuntu
-   lightGallery version - 2.7.0

### Additional context

Would be great to ignore the actual size feature when there would be a feature of a max-zoom-in factor set. Even the picture is not that big (over-zooming). With vector-based SVG's you could do nice stuff, and solve the Safari-Bug where Safari does not recognize the actual-size.

Screencast of Issue:
[zoomInMax-jumping.webm](https://user-images.githubusercontent.com/58986818/199755350-da6a2044-6184-4bd0-9b1f-a50fd93cf6af.webm)

**Comment by sachinchoolur** [comment]
Hey @mo-we,

Thank you for reporting this issue. `reset-transition` is required to retain the quality of the image on mobile devices.

But I'm able to reproduce the issue and fixed it locally. This happens only if you use zoom-in-out icons 

I'll include the fix in the next version

**Comment by sachinchoolur** [comment]
Hey @mo-we,

The issue has been fixed in version https://github.com/sachinchoolur/lightGallery/releases/tag/2.7.1-beta.1

Could you please verify?

**Comment by mo-we** [comment]
Hello @sachinchoolur sorry that i answer so late. I tested it out, and it is still the same behaviour: the full zoomed in image will jump because the `!important ` in `.lg-outer .lg-item.lg-complete.lg-zoomable .lg-dummy-img.reset-transition` overwrites the element styles (which i.m.o. should just be preserved and not be resetted.)

this rule: 
```
.lg-outer .lg-item.lg-complete.lg-zoomable .lg-image.reset-transition, .lg-outer .lg-item.lg-complete.lg-zoomable .lg-dummy-img.reset-transition {
  transform: scale3d(1, 1, 1) translate3d(-50%, -50%, 0px) !important;
  max-width: none !important;
  max-height: none !important;
  top: 50% !important;
  left: 50% !important;
}
```

overwrites the transform in element style:
```
element {
  width: 1600px;
  height: 1200px;
  transform: scale3d(1.69851, 1.69851, 1);
}
```
thanks for looking into this
