### ISSUE TITLE
Image are shaking

### ISSUE THREAD

**Issue by jksenthilraja** [sachinchoolur/lightGallery#510]
Image are shaking, when I click Zoom In and Zoom Out Button how to solve?

**Comment by sachinchoolur** [comment]
Hi @jksenthilraja ,
Please check the bellow link on your browser and let me know the result.
http://codepen.io/sachinchoolur/full/VmyJZL

**Comment by whimsicaldreamer** [comment]
@sachinchoolur, the code pen works smooth irrespective of the demo in the website. It would be nice to have something like tap to zoom feature.

**Comment by sachinchoolur** [comment]
Hi guys,
The issue has been fixed. Please use the latest version of [lg-zoom](https://github.com/sachinchoolur/lg-zoom) and lightgallery.css

**Comment by whimsicaldreamer** [comment]
@sachinchoolur I am using the latest version of lg-zoom and lightgallery.css but somewhat the issue still persists.

**Comment by whimsicaldreamer** [comment]
Ok, according to the mails exchanged, we need to use `useLeftforZoom: false` and the problem gets sorted.
