### ISSUE TITLE
Error when closing gallery

### ISSUE THREAD

**Issue by OXAYAZA** [sachinchoolur/lightGallery#849]
In Chrome 71, exception is thrown when invoking `document.exitFullscreen()` while not in full-screen mode.
https://github.com/jpilfold/ngx-image-viewer/issues/23#issuecomment-446899261

**Comment by sanastasiou** [comment]
I can confirm. Exact same bug.

**Comment by sanastasiou** [comment]
Will fix it locally with one of the mentioned workarounds.

**Comment by aj1991** [comment]
Same here. Any plans to fix this? :)

**Comment by zslabs** [comment]
@sachinchoolur It looks like https://github.com/jpilfold/ngx-image-viewer/issues/23 had some potential fixes for this issue.

**Comment by stat1x** [comment]
Same here.

**Comment by stevepcooke** [comment]
I get this error sent to the DOM when closing the full screen view in Chrome

Uncaught (in promise) TypeError: Document not active
    at Fullscreen.exitFullscreen 
(lg-fullscreen.js:75)
    at Fullscreen.destroy (lg-fullscreen.js:107)
    at Function.<anonymous> (lightgallery.js:1311)
    at Function.each (jquery-3.1.1.min.js:2)
    at Plugin.destroy (lightgallery.js:1309)
    at HTMLSpanElement.<anonymous> (lightgallery.js:1244)
    at HTMLSpanElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLSpanElement.q.handle (jquery-3.1.1.min.js:3)

**Comment by stevepcooke** [comment]
I have fixed this issue by editing the  lightgallery-all.js  file changing line 1645  
From :   if (document.exitFullscreen) {
To:  if (document.fullscreenElement) {

**Comment by aj1991** [comment]
Fixing this problem in source files seems not to be the right solution

**Comment by hugolantaume** [comment]
Same here.

**Comment by zslabs** [comment]
If someone can create a PR with the fix; this can most likely get fixed a lot sooner.

**Comment by elemis** [comment]
Same here

**Comment by mafh** [comment]
+1

**Comment by sachinchoolur** [comment]
Guys, Really sorry for the delayed response. The issue has been fixed.

**Comment by yoldar** [comment]
> Guys, Really sorry for the delayed response. The issue has been fixed.

Do not forget to add lib to NPM

<img width="879" alt="screen shot 2019-02-19 at 5 26 01 pm" src="https://user-images.githubusercontent.com/1597578/53011841-8fc97380-346b-11e9-9937-0f33dd1f9bcb.png">

**Comment by sanket-webmavens** [comment]
> +1

It seems like the error still occurs if we use the all.min.js from dist/js.

**Comment by idahopotato1** [comment]
You can open the all.min.js and search for prototype.exitFullscreen=function 
and then change the {document.exitFullscreen?  
to {document.fullscreenElement? 

That fixes it.

**Comment by harsh-webmavens** [comment]
After doing that full screen function doesn't working properly
